// carrier_db.js — Amazon DLZ3
// Database Carrier SCAC → Nome
// Versione pulita senza caratteri speciali

var CARRIER_DB = {
    "ASPIC": "LOGISTICA & TRASPORTI SPINELLI CATALDO",
    "AFAGS": "GATTI FILASTRO SRL",
    "NROMA": "NORD ROMA TERMINAL",
    "ABPRP": "ABPRP ATSEU",
    "AGPUE": "AGPUE ATSEU",
    "AAFLI": "AAFLI ATSEU",
    "ACQSM": "Eurotrade 24 GmbH",
    "ADEMI": "2D Express Dabrowscy sp.j.",
    "ACSAL": "Battimelli Carmine",
    "AXQSP": "Bolid Damian Bomba",
    "AQAAH": "ELISTORCAR TRANSPORT SP. Z O.O.",
    "AALJF": "Euro-Transport Sp. z o.o.",
    "AFQKH": "FTU EURO TRANS HANDZEL",
    "APRBL": "Galaxi Haulage Limited",
    "AECNE": "H&S HAULAGE LTD",
    "ANGIT": "Ibiza-Speed Sp. z o.o.",
    "AXRPO": "Incampo Giovanni",
    "ACEID": "Kompas Spedycja Sp. z o.o.",
    "AEBFR": "LEN Logistics Patrycja Lach",
    "AJMCV": "Marcin Kucharski Megam",
    "AEABS": "MIEDZYNARODOWY TRANSPORT DROGOWY MARIUSZ PAPIS",
    "AAUMA": "Modica Salvatore",
    "AJDNT": "N&S LOGISTICS",
    "AZGKE": "PASQUALE CALIA",
    "ASHDC": "PRO-PANDA SRL",
    "ATACO": "Przedsiebiorstwo Handlowo-Transportowe TRACOM",
    "ANWRO": "Revox ltd",
    "AWAPO": "SC Thermo Tranzit SRL",
    "AFZVG": "SMART DELIVERY SP Z O.O.",
    "ASTZO": "Stepien Sp. z o.o.",
    "AOXRP": "Tako Logistics Sp zoo",
    "ARRKB": "TRANSPORT GABIN",
    "APQPR": "Zaklad Produkcyjno Handlowo Uslugowy ANNMAT",
    "ASKCL": "Bartek Lewandowski uslugi transportowe",
    "ASEDG": "ARDEL ADRIANA LECH RENATA KRUZ SPOLKA JAWNA",
    "ACHZO": "Christopher sp. z o.o.",
    "ACODH": "DARTRANS DARIUSZ KOPEC",
    "AKIEE": "EM-TRANS Marcin Zegan",
    "AJAAR": "Jar-Trans Agnieszka Rost",
    "AKOBK": "KorbiTrans Blazej Korbanek",
    "AVQYD": "MOL-TRANS MARIOLA SKWIROWSKA",
    "AMOPZ": "MOTOHOL Pawel Zaluski",
    "AICOC": "PRESTO ANDRZEJ PERUGA",
    "AVEIS": "Sekpol Lewonczyk Spolka Jawna",
    "ATMTD": "Tornado-Trans Robert Kopacki",
    "ACXVQ": "TRANS AUTO SERWIS Sp. z o.o.",
    "AUVHR": "UVE Hubert Rutkowski",
    "AWITC": "WIKTOR Transport Chlodniczy",
    "AWJTN": "X-CAR IGOR PAWEL GRETKA",
    "AGOMX": "ZIOMEK TRANS TRANSPORT DROGOWY Michal Ziomek",
    "ALQFI": "JUSIUK Zbigniew Jusiuk",
    "AJWFY": "1 NVB Transport Ltd",
    "ARHGV": "1 PROTRANS LTD",
    "AYFLX": "123 Express LTD",
    "AYNRR": "123RS sp z o.o.",
    "AMUQK": "13Garare Kamil Kaczynski",
    "AFEYD": "19S46 Ltd",
    "AQDYO": "1ATP sp. z o.o.",
    "AVVCA": "1st Class Transport (UK) Limited",
    "AOTSS": "2009 OCEAN TRANSPORT SPAIN S.L.",
    "AJPXT": "21 European Transport",
    "ATRIO": "24/7 Transportation ltd",
    "AFJUL": "264 HAULAGE LIMITED",
    "ASJSX": "2B SOLUTIONS SP. Z O.O.",
    "AFTRR": "2F TRASPORTI SRL",
    "AXZBN": "2FAST LOGISTICS LTD",
    "AVSTY": "2GT TRANSPORT LTD",
    "AGKJY": "2MFRET",
    "AMPTT": "2MPJ Transport Ltd",
    "ACWJP": "2RE TRANSPORTS",
    "ASNTR": "2SN TRANSPORTS",
    "AHZPJ": "3 MARCHANDISES TRANSPORT CONTINENTAL",
    "ANDCG": "300logistyka Przemyslaw Sztadelman",
    "AWBDX": "3125 Haulage ltd",
    "ATAEP": "35 transports et entreposage",
    "ALLTC": "365 Logistics ltd T/A Cheetah Logistics",
    "AMHMM": "3D trasporti",
    "ASKGH": "3D ZOOM TRANSPORTS",
    "AFTHA": "3FT Haulage LTD",
    "AGTSI": "3GL Transport (Scotland) Limited",
    "APRFA": "3NETRA LOGISTICS",
    "AUMZV": "4 Logistic sp. z o.o.",
    "AGHXA": "4 RATAI Transport GmbH",
    "AMTDW": "4S Transport Sp. z o.o.",
    "AFFCN": "4ST LTD",
    "AZRIL": "4U TRAVEL SERVICES PRIVATE LIMITED",
    "ALOIL": "66 Logistics Ltd",
    "ARDKT": "7RDK LTD",
    "APPND": "816 Logistics Limited",
    "APQTU": "852 Haulage Ltd",
    "AGZBO": "911 LOGISTICA",
    "AIDTD": "A & A Transport UK Midland Ltd",
    "ADDAM": "A & B Haulage Ltd",
    "AADTP": "A & D TRASPORTI S.R.L.",
    "ATEVV": "A & M Logistics Arkadiusz Waleryszek",
    "ABGTA": "A & S Guterverkehr GmbH",
    "AQRWI": "A 94 LTD",
    "AAABL": "A Abraham Ltd",
    "AIFHJ": "A Aujla Transport Ltd",
    "ABTFH": "A brookside haulage limited",
    "AGFJO": "A E CHILLED LIMITED",
    "AGLVG": "A J Kelly Transport Ltd",
    "AJEWY": "A J Slavin & Sons Ltd",
    "AAJWT": "A J Ward Transport Ltd",
    "AANMV": "A K ENTERPRISES",
    "ASMFQ": "A K Logistics Limited",
    "AALGS": "A Logistics LT",
    "AANLT": "A N Logistics LTD",
    "AABVM": "A S Transport Krajowy i Miedzynarodowy",
    "AJNKI": "A Sekhon Ltd",
    "AATTT": "A Thompson Transport LTD",
    "AMTWO": "A TO B TRANSPORT AND RECOVERY LTD",
    "ABWIR": "A Veer transport limited",
    "AAWPT": "A W Pallant Transport",
    "ANVIF": "A Whitehead Transport Ltd",
    "AYGPZ": "A Z Logistic EOOD",
    "AXZGT": "A&A EXPERT TRASPORTI DI ANDRONIC ANDREI",
    "ARFCX": "A&A Transport Sp. z o.o.",
    "AACCT": "A&C Carriage Ltd",
    "ABWDA": "A&C LOGISTIK LTD",
    "ANALC": "A&D LOGISTICS SP. Z O.O.",
    "AIVSA": "A&F Transport NW LTD",
    "AAMGL": "A&M GTRANS LTD",
    "AOAMD": "A&N foody ltd",
    "AOSMH": "A&r solutions ltd",
    "AUKWS": "A&S Solutions GmbH",
    "AFIUF": "A&Z transport",
    "AAPRR": "A'pro Transport",
    "AANDG": "A+G Transporten B.V.",
    "AAHGM": "A+H GmbH",
    "AOGOX": "A-Logistics DE",
    "AUANI": "A-S-T MARCIN NIEDBALA",
    "AXQCL": "A-TRANS SP. Z O.O.",
    "AWYJR": "A.R.J SP. Z O.O.",
    "AATJF": "A.T. JIMENEZ FORNIELES S.L.",
    "ADEXX": "A.C.M. TRANS LTD",
    "ADLXV": "A.D.D. TRANSPORT LTD",
    "AKPJJ": "A.E.V. Srl",
    "AAIMK": "A.I.M(UK)Ltd",
    "AMMXY": "A.K.J Transport LTD",
    "AEVIS": "A.K.TRANS ADAM KORGUL",
    "AJEPM": "A.M. TRASPORTI SRL",
    "AOVHS": "A.M.D. TRASPORTI SRLS",
    "AAMSR": "A.M.G. SPEED SRL",
    "AAWSO": "A.M.P. WIECZOREK SPOLKA Z O.O.",
    "AXJHO": "A.MAC Transport Limited",
    "AAQIT": "A.Q.I Transports",
    "AOMRB": "A.S. Trans Sp. z o.o.",
    "ANJPD": "A.S. Transport Aleksander Strzelecki",
    "AEHCN": "A.S.A TRASPORTI SRL",
    "ANXJY": "A1 Transport London ltd",
    "ANZLO": "A2bee logistics ltd",
    "AMXUE": "A2C TRANSPORTS",
    "AATTR": "A2T TRANSPORT",
    "AUJZS": "aa haulage services ltd",
    "AXYJL": "AA LOGISTICS MIDLANDS LTD",
    "AINNQ": "AA TRANSPORT",
    "AADST": "AAA Delivery Services Ltd",
    "AAAGE": "AAC GLOBE EXPRESS",
    "AAUBM": "AAC UK Business Limited",
    "AAATT": "AAD Transport Ltd",
    "AAAKL": "Aakash logistics",
    "ADTSX": "AANKAD TRANSPORTS MEDITERRANEENS",
    "AXWIE": "AB EXPRESS",
    "AQLNS": "AB EXPRESS",
    "AKALC": "AB Group Sp.z o.o.",
    "AJFUM": "AB Logistics Service",
    "ABEQU": "AB QUICK LOGISTICS PRIVATE LIMITED",
    "AABTO": "AB Transports",
    "AQSDQ": "AB TRASPORTI DI BARBU ALEXANDRU",
    "AABKW": "AB-TRANS Krzysztof Wojnarowicz",
    "AMNUV": "AB5 TRANSPORTS",
    "AKLWQ": "ABAKUS LOGISTICS SP Z O O",
    "AABAE": "Abazi srl",
    "AEENR": "ABC LOGISTICS",
    "AGRFE": "ABC TRANS LTD",
    "AABTT": "Abc Transport Tomkiewicz",
    "AWRYT": "Abdurrahman Yildirim",
    "ATQLZ": "ABE SPEDITION SRL",
    "ARDII": "ABEILLE RUSH",
    "AABRR": "ABENI TRANS SRL",
    "AYDWG": "Abex logistics limited",
    "AZUVC": "Abhay Service",
    "AJIVE": "Abi Text Concept SRL",
    "ATTUF": "ABM TRANSPORT LTD",
    "AABTP": "ABM Transport Ltd",
    "AYMCL": "ABP Transport Ltd",
    "AESWI": "Abraham Strathmann",
    "ABPCT": "Abro transport limited",
    "ATXUS": "Abru Line bv",
    "ACXJE": "ABS Logistic Solutions",
    "AXPYM": "ABS Logistics",
    "AABTS": "ABS TRANS SAB",
    "AABFS": "ABSOLUTE FIDES SRL",
    "AIWIP": "Abu trans Ltd",
    "AFLQO": "ABYTRANS PERSONELL LIMITED",
    "AACDD": "AC DRIVE LTD",
    "AACIN": "AC INTERNATIONAL",
    "AZAVA": "AC MEGA-TRANS SP.Z.O.O",
    "AASFT": "AC TRANSPORT",
    "ASGUF": "Accelero Logistics LTD",
    "AUEQD": "ACCORD Przemyslaw Stankiewicz",
    "ANDUI": "ACDC TRANSPORT MK Sp. z o.o.",
    "ALPNI": "Ace logistics Wolverhampton Ltd",
    "AACJT": "ACJ TRANS",
    "ADNDS": "ACLW Transport Ltd",
    "AACLD": "ACM LOGISTICS LTD",
    "ACPKW": "ACORD-TRANS SP. Z O.O.",
    "ACTIN": "Acting sp. z o.o.",
    "ALUHF": "Active Enterprises",
    "AYKTZ": "ACTRANS",
    "AEVBP": "ACTUALITY WORKS S.L.",
    "AENLY": "acw haulage ltd",
    "AACSP": "Ad cargo sp zo.o.",
    "AJOPI": "Ad haulage ltd",
    "AADLT": "ad loc tp",
    "AIAWJ": "AD TRACTION",
    "ATUIR": "AD TRANS",
    "AAMTK": "Ad-Mar Transport Krajowy i Miedzynarodowy",
    "FERCA": "Fercam S.p.A.",
    "BRTXX": "BRT",
    "DHLF":  "DHL Freight GmbH",
    "DHLPE": "DHL PARCEL",
    "DHLFF": "DHL Freight France SAS",
    "DHLTS": "DHL Freight GmbH Euronet",
    "DHLGF": "DHL Global Forwarding",
    "DPSTD": "DHL Paket",
    "DHLIT": "DHLIT",
    "DHLES": "DHL Express",
    "DHLC":  "DHL Express International",
    "DPDXX": "DPD Group UK",
    "DPDBE": "DPD Benelux",
    "ADPFA": "DPD France",
    "HRMUK": "EVRi",
    "RMLGB": "ROYAL MAIL",
    "UPSN":  "UPS Parcel",
    "AUPPR": "UPS Parcel France",
    "AUPPI": "UPS Parcel Italy",
    "AUSUL": "UPS SCS UK LTD",
    "UPSEU": "UPS EU",
    "STOB":  "Eddie Stobart Logistics Plc",
    "STOEU": "Eddie Stobart Logistics Europe NV",
    "AJSZU": "Eddie Stobart Logistics Germany GmbH",
    "MARIT": "Maritime Transport",
    "MZTU":  "Maritime Transport Ltd",
    "SENN":  "sennder Deutschland GmbH",
    "AXXTX": "sennder Italia S.r.l.",
    "SEUR":  "SEUR",
    "CORRX": "CORREOS EXPRESS S.A.",
    "CORRS": "CORREOS",
    "DACHS": "Dachser SE",
    "GEFCO": "GEFCO FR",
    "SCHEN": "Schenker Deutschland AG",
    "AGLDB": "Schenker Luxemburg GMBH",
    "ADBSR": "DB Schenker France",
    "KHNA":  "Kuehne Nagel Ltd",
    "KHNN":  "KuehneNagel",
    "AKNFH": "Kuehne + Nagel UK",
    "AKNSZ": "Kuehne + Nagel Sp. z o.o.",
    "AKNAC": "Kuehne + Nagel AG Co. KG",
    "DRUFR": "Kuehne Nagel Road",
    "CHRB":  "C.H. Robinson Europe BV",
    "ARCES": "Arcese trasporti spa",
    "AAGUK": "Amazon.Com Inc Amazon Freight",
    "AFXUK": "Amazon Freight Exchange",
    "AGLRN": "Amazon Freight dummy",
    "ASTPG": "Amazon Freight Exchange AG",
    "AAFED": "Amazon Freight Exchange DE",
    "AAMSF": "AMAZON SEA",
    "AKSYJ": "Amazon EU RLB PM Test",
    "ANKJB": "GEODIS",
    "AOIVR": "Geodis CL Italia S.p.A",
    "AQVYC": "Geodis France",
    "FRAEX": "Geodis France Express",
    "XPOES": "XPO TRANSPORT SOLUTIONS SPAIN SL",
    "ATBWO": "XPO Logistics IPCP Carrier",
    "HALSP": "Halsped GmbH",
    "WABER": "Waberers International Nyrt",
    "WALLE": "Wallenborn Transport",
    "SDAXX": "SDA Express Courier S.P.A.",
    "ACBGL": "An Post",
    "POLPO": "Poczta Polska S.A.",
    "FIPS":  "Posti Oy",
    "LPOST": "Coliposte",
    "MRELA": "MONDIAL RELAY",
    "TNTFR": "TNT EXPRESS FRANCE",
    "TNTXX": "TNTXX",
    "TOFLX": "trans-o-flex Express GmbH Co. KGaA",
    "PLTLN": "Palletline",
    "PAFLG": "PAF Logistics",
    "MSKEU": "Maersk SCM EU",
    "LOGSY": "Logsystems GmbH",
    "GLSXX": "GLS Enterprise Srl",
    "ASMES": "GLS SPAIN",
    "COLPR": "COLISPRIVE",
    "RELCO": "RELAIS COLIS",
    "FLASH": "FLASH TAXICOLIS",
    "SIMAR": "SIMAR EXPRESS SOLUTIONS",
    "EURGP": "EUROPE GROUP Sp. z o.o.",
    "OWENS": "Owens Road Services Ltd",
    "BUCKX": "Buckingham Logistics Limited",
    "TOURL": "TOURLINE",
    "POFM":  "PO Ferrymasters Limited",
    "TROTA": "AT TROTA SA",
    "ELEVP": "ELEVEN Logistics Group Sp. z o.o.",
    "GRUND": "Grund I Synowie Sp. zo.o. Sp. K.",
    "LOCOX": "Locotranssped Sp. Z O.O.",
    "SAWA":  "Sawa Logistics Sp. z o.o.",
    "SAFEP": "Safe Logistics Sp. z o.o.",
    "NATAP": "NATANEK NOVA SP ZOO SK",
    "DUNA":  "Transduna Sp. z o.o.",
    "GRAN":  "GRAND spolka z ograniczona odpowiedzialnoscia",
    "DETR":  "Demotrans Spedycja Transport Pawel Kaleta",
    "POCK":  "Pollock Scotrans Ltd",
    "WABER": "Waberers International Nyrt",
    "CAPIT": "CAPITRANS",
    "CRFC":  "Care Freight Carriers",
    "HARGO": "Hari Cargo Carrier",
    "HARSH": "Harsh Transport Pvt Ltd",
    "SHIVA": "Shiv Shakti Cargo Service",
    "NCTY":  "New City Carrier P Limited",
    "PADMA": "PADMA TRAVELS",
    "DHIR":  "Dhir Roadways",
    "RUBY":  "Ruby ROADLINES",
    "OMTR":  "OM Transport Company",
    "GOLD":  "Golden Aero Logistics",
    "VAISH": "Vaishali Transcarriers Private Limited",
    "CASPN": "Caspian Supply Chain Pvt Ltd",
    "CISLA": "Cisla Cargo Logistics",
    "FRNDS": "Friends Group Enterprises",
    "RYCL":  "Royce Logistics",
    "MASPL": "Mass Express Cargo Pvt. Ltd.",
    "MITUJ": "Mituj Marketing Pvt. Ltd.",
    "VIIA":  "VIIA",
    "PINDE": "PIN AG",
    "EFRW":  "Efret Ltd",
    "LSNPL": "Loadshare Networks Private Limited",
    "TIRANGA": "TIRANGA LOGISTICS PRIVATE LIMITED",
    "FTRAC": "Fast Track Logistics",
    "DGEEX": "DG EUROPE EXPRESS",
    "TMFOP": "TMFOP SAS",
    "RBLPL": "RyBlue Logistics Pvt.Ltd",
    "ALOAU": "Logistica Garsomur SLU",
    "AMREY": "LOGIST TRANS CITY S.L.",
    "ALOGO": "LOGISTICA GRILLO SLU",
    "AAGQC": "LOGISTICA JUAN RUIZ S.L.",
    "ASYIY": "LOGISTICA PACO LOPEZ S.L.",
    "ALOUS": "Logistica Ursu S.L.",
    "AUPWF": "LOGISTICA Y TRANSPORTE CESPEDES SL",
    "AKIBW": "Logistics consult ltd",
    "ARCHH": "LOGISTICS KINGDOM LIMITED",
    "AAUMS": "Auta Marocchi spa",
    "AFDWZ": "AUTOTRASPORTI AUTUORI ANIELLO",
    "AAUBR": "AUTOTRASPORTI BOMMARTINI SRL",
    "AAUOE": "Autotrasporti Bonello srl",
    "AIXNN": "Autotrasporti Borghi Srl",
    "AZAZV": "Autotrasporti Borrelli Fulvio Srl",
    "AACGP": "Autotrasporti c/terzi Giorgio Pellitteri",
    "AAUCN": "Autotrasporti Calia Nunzio",
    "AXIRZ": "AUTOTRASPORTI CALIA SAVERIO",
    "AOPFN": "Autotrasporti Carestia Srl",
    "ANJKW": "Autotrasporti Costa Cardone Rosario",
    "AIDMA": "AUTOTRASPORTI CRISTIAN DI MISTREANU SORIN",
    "AADNS": "Autotrasporti de nisi ssrl",
    "AXPJF": "AUTOTRASPORTI F.lli VERDONI SNC",
    "AAFCR": "Autotrasporti Fratelli Convertini S.R.L.",
    "AURYL": "Autotrasporti luca boriati",
    "AMAHH": "AUTOTRASPORTI M3A S.R.L.",
    "AAMRC": "AUTOTRASPORTI MAIMONE ROSARIA CONCETTA",
    "AAUMO": "AUTOTRASPORTI MAIONE SAS",
    "AAUMU": "autotrasporti manna giuseppe",
    "AYNRC": "AUTOTRASPORTI MARCAZZAN F.LLI SRL",
    "AAUAU": "Autotrasporti Martin Gianluca",
    "AAUME": "Autotrasporti Menegatti S.r.l.",
    "AGVMK": "Autotrasporti Meoli Mauro",
    "AAUPQ": "Autotrasporti Paladino Pasquale",
    "AAUPA": "Autotrasporti Pellini sas",
    "AAPCE": "AUTOTRASPORTI PICCOLI CLAUDIO E FIGLI SRL",
    "AAUPD": "Autotrasporti Pierdomenico srl",
    "ASUWM": "Autotrasporti Popsor Di Nelu Gabriel",
    "AAURS": "AUTOTRASPORTI RDS S.R.L.",
    "AUCRK": "AUTOTRASPORTI RIVIELLO ANTONIO C. SNC",
    "ASVVT": "Autotrasporti S.Angela srl",
    "AAUIR": "Autotrasporti Sainato Roma srl",
    "AASMS": "AUTOTRASPORTI SINISI MICHELE S.R.L.",
    "AASLF": "Autotrasporti Spinosa Luigi F. Srl",
    "AERSV": "AUTOTRASPORTI TIRSINA RUSLAN",
    "ANVAN": "AUTOTRASPORTI TIRSINA SERGIU",
    "AQGNR": "AUTOTRASPORTI V.V DI VOICU VITALIE",
    "AOASO": "autotrasporti valchiese srl",
    "AIDQA": "Autotrasporti Veneruso Sergio",
    "AAUTV": "Autotrasporti Vitaliano S.r.l.",
    "AFOMK": "autotrasporticastello srl",
    "AADFL": "Autrasporti di Fratarcangeli Loreto",
    "AVMWO": "Autuori Massimo",
};

// ───────────────────────────────────────────────
// FUNZIONI HELPER — usate da cmr_generator.js
// ───────────────────────────────────────────────

function parseScac(raw) {
    if (!raw) return '';
    return raw.trim().split(/[\s(]/)[0].toUpperCase().trim();
}

function findCarrier(scacRaw) {
    var scac = parseScac(scacRaw);
    if (!scac) return '';
    if (CARRIER_DB[scac]) return CARRIER_DB[scac];
    var partial = Object.keys(CARRIER_DB)
        .find(function(k) {
            return k.startsWith(scac.slice(0, 4));
        });
    return partial ? CARRIER_DB[partial] : '';
}

function searchCarrier(query) {
    if (!query || query.length < 2) return [];
    var q = query.toLowerCase();
    return Object.entries(CARRIER_DB)
        .filter(function(entry) {
            return entry[0].toLowerCase().includes(q) ||
                   entry[1].toLowerCase().includes(q);
        })
        .slice(0, 10)
        .map(function(entry) {
            return { code: entry[0], name: entry[1] };
        });
   
}
 window.CARRIER_DB    = CARRIER_DB;
window.parseScac     = parseScac;
window.findCarrier   = findCarrier;
window.searchCarrier = searchCarrier;
